// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package ports

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// Member defines model for Member.
type Member struct {
	Email    *string `json:"email,omitempty"`
	Lastname *string `json:"lastname,omitempty"`
	Name     *string `json:"name,omitempty"`
}

// Project defines model for Project.
type Project struct {
	Description string    `json:"description"`
	Members     *[]Member `json:"members,omitempty"`
	Tasks       *[]Task   `json:"tasks,omitempty"`
	Title       string    `json:"title"`
}

// Task defines model for Task.
type Task struct {
	Assigned    *[]Member `json:"assigned,omitempty"`
	Description *string   `json:"description,omitempty"`
	State       *string   `json:"state,omitempty"`
	Title       *string   `json:"title,omitempty"`
}
