openapi: '3.0.0'
info:
  title: Project
  version: "1.0"
  description: TODO
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
security:
  - bearerAuth: []
paths:
  /projects:
    get:
      operationId: getAllProjects
      responses:
        '200':
          description: A list of projects 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project" 
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error" 
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Project:
      type: object
      required: [title,description]
      properties:
        title:
          type: string
        description:
          type: string
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
        members:
          type: array
          items:
            $ref: '#/components/schemas/Member'
      Task:
        type: Object
        required: 
        properties:
          title:
            type: string
          description:
            type: string
          state:
            type: string
          assigned:
            type: array
            items: 
              $ref: '#/components/schemas/Member'
        Member:
          type: object
          required: 
          properties:
            name: 
              type: string
            lastname:
              type: string
            email:
              type: string
    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string